repositories:
- name: codecentric
  url: https://codecentric.github.io/helm-charts

releases:
- name: keycloak
  namespace: keycloak
  chart: codecentric/keycloakx
  version: 2.2.1
  timeout: 300
  atomic: true
  values:
    - values.yaml